name: Deploy to IPFS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          npm install

      # Étape 4 : Déployer sur IPFS
      - name: Deploy to IPFS
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
        run: |
          # Crée un dossier zip à partir du contenu
          zip -r site.zip .
          # Déploie sur Pinata
          node -e "
          const pinataSDK = require('@pinata/sdk');
          const fs = require('fs');
          const pinata = pinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_API_SECRET);
          const readableStreamForFile = fs.createReadStream('./site.zip');
          pinata.pinFileToIPFS(readableStreamForFile, {
            pinataMetadata: { name: 'MyWebsite' }
          }).then((result) => {
            console.log('Website deployed to IPFS:', result);
          }).catch((err) => {
            console.error('Error deploying site:', err);
          });
          "
